book_manager/urls.py
from django.urls import path
from . import views
from django.conf.urls import handler404

urlpatterns = [
     path('', views.index, name='index'),
     path('book_management/', views.book_management, name='book-management'),
     path('book_management/search-results', views.SearchBooksResultsView.as_view(), name='book-results'),
     path('book_management/create-book', views.create_book, name='create-book'),
     path('book_management/update-book/<int:pk>', views.UpdateBook.as_view(), name='update-book'),
     path('book_catalog/', views.BookCatalog.as_view(), name='book-catalog'),
     path('book_catalog/<int:pk>', views.BookInfo.as_view(), name='book-info'),
     path('author_management/', views.author_management, name='author-management'),
     path('author_management/create-author', views.create_author, name='create-author'),
     path('author_management/author-results', views.SearchAuthorResultsView.as_view(), name='author-results'),
     path('author_management/update-author/<int:pk>', views.UpdateAuthor.as_view(), name='update-author'),
     path('author_catalog/', views.AuthorCatalog.as_view(), name='author-catalog'),
     path('author_catalog/<int:pk>', views.AuthorInfo.as_view(), name='author-info'),
     path('contact/', views.contact, name='contact')
]

inventory_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book_manager/', include('book_manager.urls')),
    path('', RedirectView.as_view(url='book_manager/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'book_manager.views.error_404_handler'
handler500 = 'book_manager.views.error_500_handler'

book_manager/models.py
from django.db import models
from django.forms.models import ModelForm
from django.urls import reverse 

# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=100, help_text='Enter a book genre')

    def get_absolute_url(self):
        return reverse('genre-info', args=[str(self.id)])

    def __str__(self):
        return self.name

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField('Birth', null=True, blank=True)
    date_of_death = models.DateField('Death', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-info', args=[str(self.id)])
    
    def __str__(self):
        return f'{self.last_name}, {self.first_name}'
    

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    synopsis = models.TextField(max_length=1000, help_text='A summary of the book content.')
    isbn = models.CharField('ISBN', max_length=13, unique=True, help_text='13-digit ISBN')
    price = models.DecimalField('Price', max_digits=5, decimal_places=2)
    quantity = models.IntegerField('Quantity', help_text='Quanity in stock.')
    genre = models.ForeignKey(Genre, help_text='Select genre.' , on_delete=models.SET_NULL, null=True)

    def get_absolute_url(self):
        return reverse('book-info', args=[str(self.id)])

    def __str__(self):
        return self.title
    
class SupportTicket(models.Model):
    email = models.EmailField(max_length=100)
    topic = models.CharField(max_length=200)
    message = models.TextField(max_length=500)
 

book_manager/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from book_manager.models import SupportTicket
from book_manager.views import Book, Author

class CreateBook(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30)
    date_of_birth = forms.DateField( required=True)
    date_of_death = forms.DateField( required=False)

    def __init__(self, *args, **kwargs):
        super(CreateBook, self).__init__(*args, **kwargs)
        self.fields['author'].required = False

    def clean(self):
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        date_of_birth = self.cleaned_data.get('date_of_birth')
        date_of_death = self.cleaned_data.get('date_of_death')


        obj, created = Author.objects.get_or_create(first_name=first_name, last_name=last_name, date_of_birth=date_of_birth, date_of_death=date_of_death)
        self.cleaned_data['author'] = obj

        return super(CreateBook, self).clean()

class CreateAuthor(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'
        help_texts = {
            'first_name': _('Required'),
            'last_name': _('Required'),
            'date_of_birth': _('Required')
        }

class ContactForm(forms.ModelForm):
    class Meta:
        model = SupportTicket
        fields = '__all__'

        help_texts = {
            'email': _('Required'),
            'topic': _('Required'),
            'message': _('Required')
        }

book_manager/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail,BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.views import generic
from django.views.generic import ListView, UpdateView
from .models import Book, Author, SupportTicket
from book_manager.forms import CreateAuthor, CreateBook, ContactForm
from django.conf import settings




# Create your views here.


class BookCatalog(generic.ListView):
    model = Book
    context_object_name = 'book_catalog'
    template_name = 'book_manager/bookcatalog.html'

    def get_queryset(self):
        return Book.objects.order_by('title')

class BookInfo(generic.DetailView):
    model = Book
    template_name = 'book_manager/bookinfo.html'
    
class AuthorCatalog(generic.ListView):
    model = Author
    context_object_name = 'author_catalog'
    template_name = 'book_manager/authorcatalog.html'
    
    def get_queryset(self):
        return Author.objects.order_by('last_name')

class AuthorInfo(generic.DetailView):
    model = Author
    template_name = 'book_manager/authorinfo.html'

class UpdateBook(UpdateView):
    model = Book
    fields = '__all__'
    template_name = 'book_manager/updatebook.html'

class UpdateAuthor(UpdateView):
    model = Author
    fields = '__all__'
    template_name = 'book_manager/updateauthor.html'

class SearchBooksResultsView(ListView):
    model = Book
    template_name = 'book_manager/searchbookresults.html'
    
    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Book.objects.filter(title__icontains=query)
        return object_list

class SearchAuthorResultsView(ListView):
    model = Author
    template_name = 'book_manager/searchauthorresults.html'
    
    def get_queryset(self):
        first_name = self.request.GET.get('firstname')
        last_name = self.request.GET.get('lastname')
        object_list = Author.objects.filter(first_name__icontains=first_name, last_name__icontains=last_name)
        return object_list

class ContactView(generic.DetailView):
    model = SupportTicket
    template_name = 'book_manager/contact.html'

def create_author(request):
    
    form = CreateAuthor(request.POST or None)
    if form.is_valid():
        form.save()

        messages.success(request, 'The author has been added.')
        return redirect('create-author')

    context = {
        'form': form
    }

    return render(request, 'book_manager/createauthor.html', context=context)

def create_book(request):
    form = CreateBook(request.POST or None)
    if form.is_valid():
        form.save()

        messages.success(request, 'The book has been added.')
        return redirect('create-book')
    context = {
        'form': form
    }
    
    return render(request, 'book_manager/createbook.html', context=context)
def index(request):
    num_books = Book.objects.all().count()
    num_authors =  Author.objects.all().count()

    info = {
        'num_books': num_books,
        'num_authors': num_authors
    }
    
    return render(request, 'book_manager/index.html', context=info)

def book_management(request):
    return render(request, 'book_manager/book_management.html')

def author_management(request):
    return render(request, 'book_manager/author_management.html')

def contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            topic = form.cleaned_data['topic']
            from_email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            form.save()
            try:
                send_mail(topic, message, from_email, ['GFuentesData@gmail.com'], fail_silently=False)
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
                
            messages.success(request, 'Your question has been submitted!')    
            return redirect('contact')
    return render(request, "book_manager/contact.html", {'form': form})

def error_404_handler(request, exception):
    return render(request, 'book_manager/404.html')

def error_500_handler(request):
    return render(request, 'book_manager/500.html')

book_manager/templates/book_manager/author_management.html
{% extends 'book_manager/base/base.html' %}

{% block content %}
    <h1>Author Management</h1>
    <ul>
        <li><a href="{% url "create-author" %}">Add Author</a></li>
        <li>
            <form action="{% url 'author-results' %}" method="get">
            <label for="search">Use search for author information or to update author information</label><br>
                <div>
                    <label for="firstname">Enter first name of author: </label>
                    <input type="text" name="firstname" id="firstname" required>
                </div>
                <div>
                    <label for="lastname">Enter last name of author: </label>
                    <input type="text" name="lastname" id="lastname" required>
                </div>
                <div>
                    <input type="submit" value="Search">
                </div>
            </form>
        </li>
    </ul>
{% endblock %}

book_manager/templates/book_manager/authorcatalog.html
{% extends 'book_manager/base/base.html' %}

{% block content %}
    <h1>Author List</h1>
    {% if author_catalog %}
    <ul>
        {% for author in author_catalog%}
        <li>
            <a href="{{ author.get_absolute_url }}">{{ author.last_name}} {{author.first_name}}</a> 
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <form action="{% url 'author-results' %}" method="get">
    <label for="search">Use search for author information or to update author information</label><br>
        <div>
            <label for="firstname">Enter first name of author: </label>
            <input type="text" name="firstname" id="firstname" required>
        </div>
        <div>
            <label for="lastname">Enter last name of author: </label>
            <input type="text" name="lastname" id="lastname" required>
        </div>
        <div>
            <input type="submit" value="Search">
        </div>
    </form>

{% endblock %}

book_manager/templates/book_manager/authorinfo.html
{% extends 'book_manager/base/base.html' %}

{% block content %}
    <h1> {{author.last_name}}, {{author.first_name }} Book List</h1>
    <p>{{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %}</p>
    
    {% if author.book_set.count > 0 %}
        <ol>
            {% for book in author.book_set.all %}
                <li><a href="{% url 'book-info' book.pk %}">{{book}}</a></li>
            {% endfor %}
        </ol>
    {% else %}
        <p>No Books listed.</p>
    {% endif %}
    
    <form action="{% url 'author-results' %}" method="get">
        <label for="search">Use search for author information or to update author information</label><br>
        <div>
            <label for="firstname">Enter first name of author: </label>
            <input type="text" name="firstname" id="firstname" required>
        </div>
        <div>
            <label for="lastname">Enter last name of author: </label>
            <input type="text" name="lastname" id="lastname" required>
        </div>
        <div>
            <input type="submit" value="Search">
        </div>
    </form>

{% endblock %}

book_manager/templates/book_manager/book_management.html
{% extends 'book_manager/base/base.html' %}

{% block content %}
    <h1>Book Management</h1>
    <ul>
        <li><a href="{% url "create-book" %}">Add Book</a></li>
        <li>
          <form action="{% url 'book-results' %}" method="get">
            <label for="search">Use search for book information or to update book information</label><br>
            <input name="q" id="search"  type="text" placeholder="Search by book title">
            <input type="submit" value="search">
          </form>
        </li>
    </ul>
{% endblock %}

book_manager/templates/book_manager/bookcatalog.html
{% extends 'book_manager/base/base.html' %}

{% block content %}
    <h1>Book Inventory</h1>
    {% if book_catalog %}
    <ul>
        {% for book in book_catalog%}
        <li>
            <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    <form action="{% url 'book-results' %}" method="get">
        <label for="search">Use search for book information or to update book information</label><br>
        <input name="q" id="search"  type="text" placeholder="Search by book title">
        <input type="submit" value="search">
    </form>
{% endblock %}

book_manager/templates/book_manager/bookinfo.html
{% extends 'book_manager/base/base.html' %}

{% block content %}
    <h1>Title: {{ book.title }}</h1>
    <p><strong>Author:</strong> <a href="{% url 'author-info' book.author.pk %}">{{ book.author }}</a></p> 
    <p><strong>Synopsis:</strong> {{ book.synopsis }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Genre:</strong> {{ book.genre}}</p>
    <p><strong>Price:</strong> {{ book.price }}</p>
    <p><strong>Quantity:</strong> {{ book.quantity }}</p>

    <form action="{% url 'book-results' %}" method="get">
        <label for="search">Use search for book information or to update book information</label><br>
        <input name="q" id="search"  type="text" placeholder="Search by book title">
        <input type="submit" value="search">
    </form>
{% endblock %}

book_manager/templates/book_manager/contact.html
{% extends 'book_manager/base/base.html' %}

{% block content %}
    {% if messages %}
      <ul class="messages"  autocomplete="off">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
    {% endif %}
    
    <h1>Contact Us</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-actions">
          <button type="submit">Send</button>
        </div>
    </form>
{% endblock %}

book_manager/templates/book_manager/createauthor.html
{% extends 'book_manager/base/base.html' %}

{% block content %} 
    {% if messages %}
        <ul class="messages"  autocomplete="off">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <h1>Add Author</h1>
    <div>
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        
        </table>
        <input type="submit" value="Add Author">
    </form>
    </div>

{% endblock %}

book_manager/templates/book_manager/createbook.html
{% extends 'book_manager/base/base.html' %}

{% block content %} 
    {% if messages %}
        <ul class="messages"  autocomplete="off">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <h1>Add Book</h1>
    <div>
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        
        </table>
        <input type="submit" value="Create Book">
    </form>
    </div>

{% endblock %}

book_manager/templates/book_manager/index.html
{% extends 'book_manager/base/base.html' %}

{% block content %}
    <h2>Book Inventory Management System</h2>
    <p>
        To add or modify books click on book management link. <br>
        To add or modify author info click on author management link. <br>
        To contact tech support click on contact link. <br>
    </p>
    <h3>Total authors and books</h3>
    <ul>
        <li><strong>Books:</strong> {{ num_books }}</li>
        <li><strong>Authors:</strong> {{ num_authors }}</li>
    </ul>
    <h3>Catalogs</h3>
    <ul>
        <li><a href="{% url "book-catalog" %}" >Book Catalog</a></li>
        <li><a href="{% url "author-catalog" %}">Author Catalog</a></li>
    </ul>
{% endblock %}

book_manager/templates/book_manager/searchauthorresults.html
{% extends 'book_manager/base/base.html' %}

{% block content %}
    <h1>Results</h1>
    <ul>
        {% for author in object_list %}
        <li>      
            <a href="{{ author.get_absolute_url }}">{{ author.last_name }}, {{author.first_name}}</a> 
        </li>
        <a href="{% url 'update-author' author.id %}">Update author Info</a>
        {% endfor %}
    </ul>
{% endblock %}

book_manager/templates/book_manager/searchresults.html
{% extends 'book_manager/base/base.html' %}

{% block content %}
    <h1>Results</h1>
    <ul>
        {% for book in object_list %}
        <li>      
            <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
        </li>
        <li><a href="{% url 'update-book' book.id %}">Update Book Info</a></li>
        {% endfor %}
    </ul>
{% endblock %}

book_manager/templates/book_manager/updateauthor.html
{% extends 'book_manager/base/base.html' %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

book_manager/templates/book_manager/updatebook.html
{% extends 'book_manager/base/base.html' %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}